version: "2"

run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  sort-order:
    - linter
    - file

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - nlreturn
    - whitespace
    - gocritic
    - gocognit
    - godot

  settings:
    mnd:
      checks:
        - argument
        - case
        - condition
        - return

    errcheck:
      check-type-assertions: true
      check-blank: true

    gocognit:
      min-complexity: 15

    gocyclo:
      min-complexity: 10

    godot:
      scope: declarations
      capital: true

    revive:
      rules:
        - name: package-comments
          disabled: true

issues:
  max-same-issues: 50
  max-issues-per-linter: 100
